-- AlterTable
ALTER TABLE "CategoryAnnouncement" ALTER COLUMN "CreatedBy" SET DATA TYPE TEXT,
ALTER COLUMN "UpdatedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Domain" ALTER COLUMN "CreatedBy" SET DATA TYPE TEXT,
ALTER COLUMN "UpdateBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Faq" ALTER COLUMN "CreatedBy" SET DATA TYPE TEXT,
ALTER COLUMN "UpdateBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "FaqUser" ALTER COLUMN "CreatedBy" SET DATA TYPE TEXT,
ALTER COLUMN "UpdateBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "LoginEmail" ALTER COLUMN "CreatedBy" SET DATA TYPE TEXT,
ALTER COLUMN "UpdatedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Weblink" ALTER COLUMN "CreatedBy" SET DATA TYPE TEXT,
ALTER COLUMN "UpdatedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "WeblinkCategories" ALTER COLUMN "CreatedBy" SET DATA TYPE TEXT;
